export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_HOTEL_DATA: 'SET_HOTEL_DATA',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	RESET_HOTEL_DATA: 'RESET_HOTEL_DATA',
	REMOVE_REVIEW: 'REMOVE_REVIEW',
	ADD_REVIEW: 'ADD_REVIEW',
	LOAD_HOTEL_ASYNC: 'LOAD_HOTEL_ASYNC',
};
